import { MRT_Localization } from "material-react-table";

export const GridCustomLocalizationFileAz: MRT_Localization = {
  actions: "Hərəkətlər",
  and: "və",
  cancel: "Ləğv et",
  changeFilterMode: "Filtr rejimini dəyişdir",
  changeSearchMode: "Axtarış rejimini dəyişdir",
  clearFilter: "Filtri təmizləyin",
  clearSearch: "Axtarışı sil",
  clearSort: "Sırtı təmizlə",
  clickToCopy: "Kopyalamaq üçün klikləyin",
  collapse: "yıxılma",
  collapseAll: "Hamısını yığışdır",
  columnActions: "Sütun Fəaliyyətləri",
  copiedToClipboard: "Panoya kopyalandı",
  dropToGroupBy: "Qrupa {column} üzrə buraxın",
  edit: "Edit",
  expand: "Genişləndirmək",
  expandAll: "Hamısını genişləndir",
  filterArrIncludes: "Daxildir",
  filterArrIncludesAll: "Hamısını ehtiva edir",
  filterArrIncludesSome: "Daxildir",
  filterBetween: "Arasında",
  filterBetweenInclusive: "BetweenInclusive",
  filterByColumn: "{column} üzrə süzün",
  filterContains: "Tərkibindədir",
  filterEmpty: "Boş",
  filterEndsWith: "Bitirir",
  filterEquals: "Bərabərdir",
  filterEqualsString: "Bərabərdir",
  filterFuzzy: "Qeyri-səlis",
  filterGreaterThan: "Böyükdür",
  filterGreaterThanOrEqualTo: "Böyük və ya Bərabərdir",
  filterInNumberRange: "Arasında",
  filterIncludesString: "İçerir",
  filterIncludesStringSensitive: "İçerir",
  filterLessThan: "Az",
  filterLessThanOrEqualTo: "Az və ya Bərabər",
  filterMode: "Filtr rejimi:{filterType}",
  filterNotEmpty: "Boş deyil",
  filterNotEquals: "Bərabər deyil",
  filterStartsWith: "Başlayır",
  filterWeakEquals: "Bərabərdir",
  filteringByColumn: "{column} - {filterType} {filterValue} üzrə filtrləmə",
  goToFirstPage: "Birinci səhifəyə keç",
  goToLastPage: "Son səhifəyə keç",
  goToNextPage: "Növbəti səhifəyə keç",
  goToPreviousPage: "Əvvəlki səhifəyə keç",
  grab: "tutmaq",
  groupByColumn: "{column} üzrə qruplaşdır",
  groupedBy: "Qruplaşdırılan",
  hideAll: "hamısını gizlət",
  hideColumn: "{column} sütununu gizlət",
  max: "Maks",
  min: "Min",
  move: "hərəkət et",
  noRecordsToDisplay: "Göstəriləcək qeyd yoxdur",
  noResultsFound: "Heç bir nəticə tapılmadı",
  of: "of",
  or: "və ya",
  pinToLeft: "Sola sancaqla",
  pinToRight: "Sağa sancın",
  resetColumnSize: "Sütun ölçüsünü sıfırla",
  resetOrder: "Sifarişi sıfırla",
  rowActions: "Sıra Fəaliyyətləri",
  rowNumber: "#",
  rowNumbers: "Sıra Nömrələri",
  rowsPerPage: "Hər səhifədə görünən sətir",
  save: "Saxla",
  search: "Axtar",
  select: "Seç",
  showAll: "Hamısını göstər",
  showAllColumns: "Bütün sütunları göstər",
  showHideColumns: "Sütunları göstər/Gizlət",
  showHideFilters: "Filtrləri göstər/gizlət",
  showHideSearch: "Axtarışı göstər/Gizlət",
  sortByColumnAsc: "{column} artan üzrə çeşidləyin",
  sortByColumnDesc: "Azalan {column} üzrə çeşidləyin",
  sortedByColumnAsc: "{column} artan üzrə çeşidlənir",
  sortedByColumnDesc: "Azalan {column} üzrə çeşidlənir",
  thenBy: ", sonra ",
  toggleDensity: "Sıxlığı dəyiş",
  toggleFullScreen: "Tam ekrana keçid",
  toggleSelectAll: "Hamısını seçin",
  toggleSelectRow: "Seçmə sətirini dəyişdirin",
  toggleVisibility: "Görünürlük dəyişdir",
  ungroupByColumn: "{column} üzrə qrupdan çıxarın",
  unpin: "Açıl",
  unpinAll: "Hamısını çıxarın",
  unsorted: "çeşidlənməmiş",
  selectedCountOfRowCountRowsSelected:
    "{selectedCount} of {rowCount} sətir(s) səçilib",
};
